### ISSUE TITLE
id() fonksiyonu tanım hatası

### ISSUE THREAD

**Issue by egazioglu** [yazbel/belgeler#7]
Belgelerde `id()` için "her nesnenin kimliği eşşiz, tek ve benzersizdir." denilmiş ancak bu doğru değildir. Python, yeni tanımlanan değişkenlere adres atamadan önce, yani bellekten yer almadan önce, aynı değere ve tipe sahip başka bir değişken olup olmadığına bakar. Eğer var ise, oluşturulan yeni değişkenin adresi olarak o adresi gösterir, yok ise bellekten yeni yer alır:

```
>>> x=5
>>> a=5
>>> id(a)
1366411248
>>> id(x)
1366411248
>>> hex(id(a))
'0x5171c7f0'
>>> hex(id(x))
'0x5171c7f0'
```
Aynı şekilde, cevabı `True` veya `False` olan tüm `boolean` değişkenler için de tek bir adres kullanır:

```
>>> bool1 = True
>>> bool2 = True
>>> bool3 = False
>>> bool4 = False
>>> hex(id(bool1))
'0x516fe140'
>>> hex(id(bool2))
'0x516fe140'
>>> hex(id(bool3))
'0x516fe150'
>>> hex(id(bool4))
'0x516fe150'
>>>
```

**Comment by ismailarilik** [comment]
Haklısınız. Bazı nesneler için ID'ler aynı olabiliyor. Ancak burada bu, sanırım, kafa karışıklığını engellemek için belirtilmemiş. Ancak bir yerde belirtildiğini biliyorum. Yani bence bu bir sorun değil.
