### ISSUE TITLE
Discussions bölümü açılabilir mi ?

### ISSUE THREAD

**Issue by hwpplayer1** [yazbel/belgeler#8]
Merhaba her ne kadar forum olsa da burada yabancı dilde de konşabileceğimiz bir Discussions açılabilir mi ?

**Comment by ismailarilik** [comment]
Tabii, olabilir.

**Comment by ismailarilik** [comment]
Ama niye burası? Bu belgeler pek sık güncellenmiyor. İstihza belgelerinin olduğu repoya açılması daha mantıklı olmaz mı?

**Comment by hwpplayer1** [comment]
Burada da var olabiliriz benim anlayışıma göre siz herhangi bir ortamda açabilirseniz ve buraya da not düşebilirseniz seviniriö

**Comment by hwpplayer1** [comment]
https://github.com/yazbel/python-istihza ben forkladım ve kendi depomda açtım, buradan da bilgi ve geribildirim toplayıp geri bildirim verebilirim
